#define DOMAIN_APP_ENABLED    1
#define DOMAIN_DG_ENABLED     0
#define DOMAIN_MODBUS_ENABLED 0

#define DOMAIN_PATCH_ENABLED  1

#ifdef DEBUG
#define TRACE_LEVEL TRACE_LEVEL_DEBUG
#else
#define TRACE_LEVEL TRACE_LEVEL_MILE
#endif
